### ISSUE TITLE
From where can the theme can be downloaded for Joplin?

### ISSUE THREAD

**Issue by sanjayen** [dracula/joplin#5]
Unable to find the Dracula theme in either https://draculatheme.com/joplin or in this repository.

**Comment by findrakecil** [comment]
Hi, @sanjayen 

Dracula theme is already included in Joplin app. No need to download theme file and import to Joplin.

The web page in https://draculatheme.com/joplin and this repository content is to show you how you can activate Dracula theme in Joplin app.

Have you successfully activate Dracula theme in your Joplin app?

**Comment by sanjayen** [comment]
@findrakecil never realised that it was already available. Thank you.
